/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./services/**/*.{ts,tsx}",
    "./utils/**/*.{ts,tsx}",
    "./obsidian-colors.css",
  ],
  important: '.hermes-root',
  corePlugins: {
    preflight: false,
  },
  safelist: [
    // Add all your custom utility classes here
    'hermes-footer-bg',
    'hermes-bg-primary',
    'hermes-bg-secondary',
    'hermes-bg-secondary-alt',
    'hermes-bg-tertiary',
    'hermes-text-normal',
    'hermes-text-muted',
    'hermes-text-faint',
    'hermes-text-accent',
    'hermes-text-accent-hover',
    'hermes-border',
    'hermes-border-hover',
    'hermes-border-focus',
    'hermes-success',
    'hermes-success-bg',
    'hermes-warning',
    'hermes-warning-bg',
    'hermes-error',
    'hermes-error-bg',
    'hermes-info',
    'hermes-info-bg',
    'hermes-user-msg-bg',
    'hermes-user-msg-text',
    'hermes-hermes-msg-bg',
    'hermes-hermes-msg-text',
    'hermes-system-msg-bg',
    'hermes-system-msg-text',
    'hermes-header-bg',
    'hermes-footer-bg',
    'hermes-input-bg',
    'hermes-input-text',
    'hermes-input-border',
    'hermes-input-border-focus',
    'hermes-interactive',
    'hermes-interactive-bg',
    'hermes-interactive-hover',
    'hermes-interactive-hover-bg',
    // Add opacity variants
    'hermes-success-bg/10',
    'hermes-success-bg/20',
    'hermes-error-bg/10',
    'hermes-error-bg/20',
    'hermes-info-bg/10',
    'hermes-info-bg/20',
    'hermes-info-bg/30',
    'hermes-border/10',
    'hermes-border/20',
    'hermes-border/40',
    'hermes-bg-secondary/5',
    'hermes-bg-secondary/10',
    'hermes-bg-secondary/20',
    'hermes-bg-secondary/40',
    'hermes-bg-secondary/60',
    'hermes-bg-secondary/90',
    'hermes-bg-secondary/95',
    // Add hover states
    'hermes-hover:success',
    'hermes-hover:success-bg',
    'hermes-hover:error',
    'hermes-hover:error-bg',
    'hermes-hover:info',
    'hermes-hover:info-bg',
    'hermes-hover:interactive',
    'hermes-hover:interactive-bg',
    // Add focus states
    'focus:hermes-input-border-focus',
    // Add glass effect
    'hermes-glass',
    // Add scrollbar
    'hermes-scrollbar',
    // Add selection
    'hermes-selection',
    // Add button colors for active conversation
    'hermes-button-text-listening',
    'hermes-button-text-hover-listening',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
